services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - '8080:8080'
    restart: unless-stopped

  vane:
    image: itzcrazykns1337/vane:latest
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - data:/home/vane/data
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    restart: unless-stopped

volumes:
  data:
    name: 'vane-data'
